# Generated by Django 4.2.2 on 2023-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
